version: "3.9"

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laundrymap
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "3308:80"
    depends_on:
      - mariadb

  php:
    container_name: laundrymap-back
    environment:
      CORS_ALLOW_ORIGIN: "http://localhost:8888"

    build:
      context: ./laundrymap-back
      dockerfile: ../docker/php/Dockerfile
    volumes:
      - ./laundrymap-back:/app
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./laundrymap-back:/app
    depends_on:
      - php


  laundrymap-front:
    container_name: laundrymap-front
    build:
      context: ./laundrymap-front
      dockerfile: ../docker/react/Dockerfile
    environment:
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "8888"]
    ports:
      - "8888:8888"
    volumes:
      - ./laundrymap-front:/app:delegated
      - /app/node_modules



volumes:
  db_data:
