# nelmio_api_doc:
#     documentation:
#         info:
#             title: 'API Documentation'
#             description: 'My API description'
#             version: '1.0.0'
#         components:
#             securitySchemes:
#                 BearerAuth:
#                     type: http
#                     scheme: bearer
#                     bearerFormat: JWT
#         security:
#             - BearerAuth: []
#     areas:
#         default:
#             path_patterns:
#                 - ^/api
#             with_attribute: false 




nelmio_api_doc:
    documentation:
        info:
            title: 'API Documentation'
            description: 'My API description'
            version: '1.0.0'
        components:
            securitySchemes:
                BearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - BearerAuth: []

        paths:
            # Surcharge security : cadenas ouvert sur toutes les routes login
            /api/v1/admin/login_check:
                post:
                    security: []

            /api/v1/utilisateur/login_check:
                post:
                    security: []

            /api/v1/professionnel/login_check:
                post:
                    security: []

    areas:
        default:
            path_patterns:
                - ^/api
            with_attribute: false